name: shapefile
version: 1.0.1
description: A cross-platform streaming parser for the ESRI Shapefile spatial data format.
repository: https://github.com/luizbarboza/shapefile

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  async: ^2.10.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
